### ISSUE TITLE
Improving Instagr8 speed

### ISSUE THREAD

**Issue by ducasp** [glufke/instagr8#3]
One point that is slow is to print the text description after loading the image.... Perhaps the server could handle this as part of the image creation, adding the text? That would be two points to improve speed:

1 - Access would be faster, only one connection to the server to grab the image CHR or two if for MSX1, instead of 2 or 3 accesses

2 - There wouldn't be a need to print the text, which is slow on Basic and not so fast using BIOS functions, it could be faster using HMMC on MSX2 and better, but still not as fast as having the text already in the image

Also, as a bonus, you could have partial support to some emojis and characters

**Comment by glufke** [comment]
It's perfectly possible to have the texto coming directly from the server. I will keep this item OPEN.

**Comment by glufke** [comment]
This feature was added. Now the text comes with the images. (It will be improved in the future for better readability).
